/**
 * Maintains the benchmark history on the `benchmarks` branch: one line per
 * measured `main` commit in `history.jsonl`, plus a generated `README.md`
 * (readable on GitHub as is) and `index.html` (the trend page for GitHub Pages).
 *
 *   node scripts/bench/history.mjs last-sha DIR
 *   node scripts/bench/history.mjs append DIR summary.json
 *
 * The headline metric is InMemoryCacheRs ÷ InMemoryCache, measured in the same
 * job: it does not depend on which runner machine a night's job landed on.
 */
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const read = (dir) => {
  const file = join(dir, "history.jsonl");
  return existsSync(file) ?
      readFileSync(file, "utf8")
        .split("\n")
        .filter(Boolean)
        .map((l) => JSON.parse(l))
    : [];
};

export function lastSha(dir) {
  return read(dir).at(-1)?.sha ?? null;
}

const day = (iso) => iso.slice(0, 10);
const short = (sha) => `\`${sha.slice(0, 7)}\``;
const kib = (bytes) => `${(bytes / 1024).toFixed(1)} KiB`;

function readme(runs) {
  const latest = runs.at(-1);
  const rows = Object.entries(latest.measurements).map(
    ([label, { apollo, rs, unit }]) =>
      `| ${label.replaceAll("|", "\\|")} | ${unit === "B" ? "memory" : "time"} | ${(rs / apollo).toFixed(2)}× |`
  );
  const memory = (r) =>
    r.memoryGeomeanVsApollo == null ?
      "—"
    : `${r.memoryGeomeanVsApollo.toFixed(2)}×`;
  const failing = Object.entries(latest.checks ?? {}).filter(
    ([, c]) => c.rs === false
  );
  return [
    "# fast-gql-cache-rs benchmark history",
    "",
    "Generated by `scripts/bench/history.mjs` from the nightly benchmark of `main`",
    "(`.github/workflows/benchmark-history.yml`); do not edit by hand. The trend page is",
    "`index.html` (serve this branch with GitHub Pages).",
    "",
    `Latest: ${short(latest.sha)} (${day(latest.date)}): InMemoryCacheRs ÷ InMemoryCache = **${latest.geomeanVsApollo.toFixed(2)}×** (geometric mean of ${rows.length} measurements; below 1.00× is faster).`,
    "",
    ...(latest.memoryGeomeanVsApollo == null ?
      []
    : [
        `Memory: InMemoryCacheRs ÷ InMemoryCache = **${memory(latest)}** (geometric mean of the memory measurements; below 1.00× is smaller).` +
          (failing.length ?
            ` Failing memory checks: ${failing.map(([label]) => label).join("; ")}.`
          : ""),
        "",
      ]),
    "## Runs",
    "",
    "| Date | Commit | Rs ÷ Apollo | Memory Rs ÷ Apollo | WASM size | Node |",
    "| --- | --- | --: | --: | --: | --- |",
    ...runs
      .toReversed()
      .map(
        (r) =>
          `| ${day(r.date)} | ${short(r.sha)} | ${r.geomeanVsApollo.toFixed(2)}× | ${memory(r)} | ${kib(r.wasmBytes)} | ${r.node} |`
      ),
    "",
    `## Latest run, per measurement`,
    "",
    "| Measurement | Kind | Rs ÷ Apollo |",
    "| --- | --- | --: |",
    ...rows,
    "",
  ].join("\n");
}

export function append(dir, summary) {
  const runs = [...read(dir), summary];
  writeFileSync(
    join(dir, "history.jsonl"),
    `${runs.map((r) => JSON.stringify(r)).join("\n")}\n`
  );
  writeFileSync(join(dir, "README.md"), readme(runs));
  copyFileSync(
    fileURLToPath(new URL("trend.html", import.meta.url)),
    join(dir, "index.html")
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [command, dir, file] = process.argv.slice(2);
  if (command === "last-sha") {
    console.log(lastSha(dir) ?? "");
  } else if (command === "append") {
    append(dir, JSON.parse(readFileSync(file, "utf8")));
  } else {
    console.error("Usage: history.mjs last-sha DIR | append DIR summary.json");
    process.exit(2);
  }
}
